'From Cuis7.9 [latest update: #8266] on 6 October 2026 at 11:09:27 pm'!
'Description '!
!provides: 'DKM-Misc-ConceptMap' 1 0!
!requires: 'DKM-Core' 1 18 nil!
SystemOrganization addCategory: #'DKM-Misc-ConceptMap'!


!classDefinition: #ConceptMap category: #'DKM-Misc-ConceptMap'!
DKMPresenter subclass: #ConceptMap
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'DKM-Misc-ConceptMap'!
!classDefinition: 'ConceptMap class' category: #'DKM-Misc-ConceptMap'!
ConceptMap class
	instanceVariableNames: ''!

