'From Cuis7.5 [latest update: #7739] on 24 December 2025 at 12:08:29 pm'!
'Description '!
!provides: 'iStoaApp' 1 1!
!requires: 'DKM-Physics-GasSimulation' 1 33 nil!
!requires: 'DKM-History-Timeline' 1 6 nil!
SystemOrganization addCategory: #iStoaApp!


!classDefinition: #Stoa category: #iStoaApp!
Object subclass: #Stoa
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'iStoaApp'!
!classDefinition: 'Stoa class' category: #iStoaApp!
Stoa class
	instanceVariableNames: ''!

